###
# Prueba db
GET http://domoticloud.onrender.com/Users

###
# Prueba db
GET http://localhost:3000/Users

###
# PRUEBA DE POST Deploy
POST http://domoticloud.onrender.com/stemp
Content-Type: application/json

{
    "user": "Alan",
    "temp": "123"
}

###
# PRUEBA DE POST USUARIO
POST http://localhost:3000/usu
Content-Type: application/json

{
    "usu": "jose",
    "correo": "jose@gmail.com"
}


###
POST http://localhost:3000/stemp
Content-Type: application/json

{
    "idsensor": "1",
    "temp": "123"
}


# Alta usuario
###
POST http://domoticloud.onrender.com/usu
Content-Type: application/json

{
    "usu": "Jesus Chavez"
}


# ###
# GET http://localhost:3000/gtemp/12

# PRUEBA DE GET Deploy
###
GET http://domoticloud.onrender.com/gsignal
Content-Type: application/json

{
    "usu": "Alan",
    "signal": "hum"
}

###
GET http://localhost:3000/gsignal
Content-Type: application/json

{
    "usu": "Alan",
    "signal": "temp"
}

###
GET http://localhost:3000/usuarios

###
GET http://domoticloud.onrender.com/usuarios

###
GET http://localhost:3000/numusu

###
GET http://domoticloud.onrender.com/numusu
