name: Node.js CI

on: [push, pull_request]

jobs:
    tests:
        runs-on: windows-latest
        
        strategy:
            matrix:
                node-version: [20.x, 18.x]
            
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: '14'
            - name: npm install
              run: npm ci
            - name: test
              run: npm test